#include "esp.h"
#include <GraphMol/PartialCharges/GasteigerCharges.h>
#include <GraphMol/FileParsers/MolWriters.h>
#include <GraphMol/FileParsers/FileParsers.h>
#include <GraphMol/MolOps.h>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include "property_params.h"
#include "surface.h"
#include "utils.h"

void SurfaceESPProperty::compute(const Surface& s,
                                 std::unordered_map<std::string, std::any>& cache) {
    std::vector<double> charges;

    switch (charge_method_) {
    case ChargeMethod::XTB:
        charges = compute_xtb_charges(s);
        break;
    case ChargeMethod::RDKIT:
        charges = compute_rdkit_charges(s, cache);
        break;
    default:
        throw std::runtime_error("Unknown charge calculation method");
    }

    cache["esp_charges"] = charges;
    cache["charge_method"] = std::string(charge_method_ == ChargeMethod::XTB ? "xtb" : "rdkit");

    std::vector<double> potentials = compute_esp_potentials(s, cache);
    cache["electrostatic_potential"] = potentials;

    // Print the actual minimum and maximum electrostatic potential values
    if (!potentials.empty()) {
        auto [min_it, max_it] = std::minmax_element(potentials.begin(), potentials.end());
        (void)min_it; (void)max_it; // Suppress unused variable warning
    } else {
        std::cout << "Electrostatic potential vector is empty." << std::endl;
    }

    // Store standardized min/max values for consistent color mapping across molecules
    PropertyParams esp_params = PropertyParamsRegistry::getParams("esp");
    cache["electrostatic_potential_min"] = esp_params.min_value;
    cache["electrostatic_potential_max"] = esp_params.max_value;
}

void SurfaceESPProperty::compute(const Surface& s, std::unordered_map<std::string, std::any>& cache,
                                 ChargeMethod method) {
    std::vector<double> charges;

    switch (method) {
    case ChargeMethod::XTB:
        charges = compute_xtb_charges(s);
        break;
    case ChargeMethod::RDKIT:
        charges = compute_rdkit_charges(s, cache);
        break;
    default:
        throw std::runtime_error("Unknown charge calculation method");
    }

    cache["esp_charges"] = charges;
    cache["charge_method"] = std::string(method == ChargeMethod::XTB ? "xtb" : "rdkit");

    std::vector<double> potentials = compute_esp_potentials(s, cache);
    cache["electrostatic_potential"] = potentials;

    // Store standardized min/max values for consistent color mapping across molecules
    PropertyParams esp_params = PropertyParamsRegistry::getParams("esp");
    cache["electrostatic_potential_min"] = esp_params.min_value;
    cache["electrostatic_potential_max"] = esp_params.max_value;
}

std::vector<double> SurfaceESPProperty::compute_xtb_charges(const Surface& s) {
    // Create a unique temporary directory
    std::string temp_dir_base = "temp_esp_";
    temp_dir_base += std::to_string(std::chrono::system_clock::now().time_since_epoch().count());
    std::filesystem::path temp_dir_path(temp_dir_base);

    std::error_code ec;
    if (!std::filesystem::create_directory(temp_dir_path, ec)) {
        if (ec) {
            throw std::runtime_error("Failed to create temporary directory: " + ec.message());
        } else {
            throw std::runtime_error("Temporary directory already exists: " + temp_dir_base);
        }
    }

    try {
        // Generate molfile in temp directory
        std::filesystem::path temp_molfile = temp_dir_path / "mol.mol";
        if (!s.molecule.mol_to_molfile(temp_molfile.string())) {
            throw std::runtime_error("Failed to write molfile to temporary directory");
        }

        // Get molecule charge
        int charge = s.molecule.get_charge();
        std::string charge_str = std::to_string(charge);

        // Construct xtb command to run in temp directory
        std::string command = "cd " + temp_dir_base + " && xtb mol.mol --chrg " + charge_str +
                              " > xtb_output.log 2>&1";

        // Run xtb command
        bool success = run_command(command);

        if (!success) {
            throw std::runtime_error("xtb computation failed");
        }

        // Check if ESP file was generated
        std::filesystem::path esp_file = temp_dir_path / "charges";
        if (!std::filesystem::exists(esp_file)) {
            throw std::runtime_error("ESP file 'charges' was not generated by xtb");
        }

        // Load ESP data from temp directory
        std::vector<double> charges = load_esp(esp_file.string());

        std::filesystem::remove_all(temp_dir_path, ec);
        return charges;

    } catch (const std::exception& e) {
        std::filesystem::remove_all(temp_dir_path, ec);
        throw std::runtime_error("XTB ESP computation failed: " + std::string(e.what()));
    }

    std::error_code cleanup_ec;
    if (!std::filesystem::remove_all(temp_dir_path, cleanup_ec)) {
        std::cerr << "Warning: Failed to clean up temporary directory " << temp_dir_base << ": "
                  << cleanup_ec.message() << std::endl;
    }
    throw std::runtime_error("Unexpected code path in compute_xtb_charges");
}

std::vector<double> SurfaceESPProperty::compute_rdkit_charges(
    const Surface& s, std::unordered_map<std::string, std::any>& cache) {
    try {
        auto rdkit_mol = s.molecule.get_mol();

        std::vector<double> charges;
        charges.reserve(rdkit_mol->getNumAtoms());

        try {
            RDKit::computeGasteigerCharges(*rdkit_mol);

            for (size_t i = 0; i < rdkit_mol->getNumAtoms(); ++i) {
                auto atom = rdkit_mol->getAtomWithIdx(i);
                if (atom->hasProp("_GasteigerCharge")) {
                    double charge;
                    atom->getProp("_GasteigerCharge", charge);
                    charges.push_back(charge);
                } else {
                    throw std::runtime_error("Gasteiger charge not computed for atom " +
                                             std::to_string(i));
                }
            }

        } catch (const std::exception& e) {
            std::cout << "Gasteiger charges failed: " << e.what() << std::endl;
            std::cout << "Falling back to formal charges..." << std::endl;

            charges.clear();
            for (size_t i = 0; i < rdkit_mol->getNumAtoms(); ++i) {
                auto atom = rdkit_mol->getAtomWithIdx(i);
                charges.push_back(static_cast<double>(atom->getFormalCharge()));
            }
        }
        cache["rdkit_charge_type"] = std::string("gasteiger");
        return charges;

    } catch (const std::exception& e) {
        throw std::runtime_error("RDKit ESP computation failed: " + std::string(e.what()));
    }
}

std::vector<double> SurfaceESPProperty::load_esp(std::string_view esp_file) const {
    if (!std::filesystem::exists(std::string(esp_file))) {
        throw std::runtime_error("ESP file does not exist: " + std::string(esp_file));
    }

    std::vector<std::string> lines = load_file(esp_file);

    std::vector<double> esp;
    esp.reserve(lines.size());

    for (size_t i = 0; i < lines.size(); ++i) {
        const auto& line = lines[i];

        if (line.empty()) {
            continue;
        }

        try {
            double charge = std::stod(line);
            esp.push_back(charge);
        } catch (const std::invalid_argument& e) {
            throw std::runtime_error("Invalid ESP data at line " + std::to_string(i + 1) + ": '" +
                                     line + "' - " + e.what());
        } catch (const std::out_of_range& e) {
            throw std::runtime_error("ESP data out of range at line " + std::to_string(i + 1) +
                                     ": '" + line + "' - " + e.what());
        }
    }
    return esp;
}

std::vector<double> SurfaceESPProperty::get_esp_charges(
    const std::unordered_map<std::string, std::any>& cache) {
    auto it = cache.find("esp_charges");
    if (it == cache.end()) {
        throw std::runtime_error("ESP charges not found in cache. Run compute() first.");
    }

    try {
        return std::any_cast<std::vector<double>>(it->second);
    } catch (const std::bad_any_cast& e) {
        throw std::runtime_error("Failed to retrieve ESP charges from cache: " +
                                 std::string(e.what()));
    }
}

std::vector<double> SurfaceESPProperty::compute_electrostatic_potential(
    const std::vector<double>& charges, const std::vector<std::vector<double>>& positions,
    const std::vector<std::vector<double>>& surface_points) {
    if (charges.size() != positions.size()) {
        throw std::runtime_error("Mismatch between number of charges (" +
                                 std::to_string(charges.size()) + ") and positions (" +
                                 std::to_string(positions.size()) + ")");
    }

    if (positions.empty() || surface_points.empty()) {
        throw std::runtime_error("Empty positions or surface points vectors");
    }

    for (size_t i = 0; i < positions.size(); ++i) {
        if (positions[i].size() != 3) {
            throw std::runtime_error("Position " + std::to_string(i) +
                                     " does not have 3 coordinates");
        }
    }

    for (size_t i = 0; i < surface_points.size(); ++i) {
        if (surface_points[i].size() != 3) {
            throw std::runtime_error("Surface point " + std::to_string(i) +
                                     " does not have 3 coordinates");
        }
    }

    // Coulomb constant scaling factor (converting to appropriate units)
    // Using atomic units: 1/(4πε₀) ≈ 14.4 eV·Å/e²
    const double COULOMB_SCALING = 14.399774088621262;  // eV·Å/e²

    std::vector<double> potentials;
    potentials.reserve(surface_points.size());

    for (const auto& point : surface_points) {
        double potential = 0.0;

        for (size_t i = 0; i < charges.size(); ++i) {
            double dx = point[0] - positions[i][0];
            double dy = point[1] - positions[i][1];
            double dz = point[2] - positions[i][2];
            double distance = std::sqrt(dx * dx + dy * dy + dz * dz);

            if (distance > 1e-10) {
                potential += charges[i] / distance;
            }
        }
        potential *= COULOMB_SCALING;
        if (!std::isfinite(potential)) {
            potential = 0.0;
        }
        potentials.push_back(potential);
    }
    return potentials;
}

std::vector<std::vector<double>> SurfaceESPProperty::get_atomic_positions(const Surface& surface) {
    auto rdkit_mol = surface.molecule.get_mol();
    if (!rdkit_mol) {
        throw std::runtime_error("Failed to get RDKit molecule for atomic position extraction");
    }

    if (rdkit_mol->getNumConformers() == 0) {
        throw std::runtime_error("Molecule has no conformers for atomic position extraction");
    }

    // Get the conformer used by the surface
    const RDKit::Conformer& conf = rdkit_mol->getConformer(surface.conformer_id);
    int num_atoms = conf.getNumAtoms();

    std::vector<std::vector<double>> positions;
    positions.reserve(num_atoms);

    for (int i = 0; i < num_atoms; ++i) {
        const RDGeom::Point3D& pos = conf.getAtomPos(i);
        positions.push_back({pos.x, pos.y, pos.z});
    }

    return positions;
}

std::vector<std::vector<double>> SurfaceESPProperty::get_surface_point_coordinates(
    const Surface& surface) {
    std::vector<std::vector<double>> coordinates;
    coordinates.reserve(surface.vertices.size());

    for (const auto& vertex_pair : surface.vertices) {
        const auto& vertex_data = vertex_pair.second;
        const std::vector<double>& coords_normals = vertex_data.second;

        // Each vertex contains [x, y, z, nx, ny, nz], we only want [x, y, z]
        if (coords_normals.size() >= 3) {
            coordinates.push_back({coords_normals[0], coords_normals[1], coords_normals[2]});
        } else {
            throw std::runtime_error("Invalid vertex data: insufficient coordinates");
        }
    }

    return coordinates;
}

std::vector<double> SurfaceESPProperty::compute_esp_potentials(
    const Surface& surface, std::unordered_map<std::string, std::any>& cache) {
    std::vector<double> charges = get_esp_charges(cache);

    std::vector<std::vector<double>> positions = get_atomic_positions(surface);

    std::vector<std::vector<double>> surface_points = get_surface_point_coordinates(surface);

    std::vector<double> potentials =
        compute_electrostatic_potential(charges, positions, surface_points);
    return potentials;
}

std::vector<double> SurfaceESPProperty::get_esp_potentials(
    const std::unordered_map<std::string, std::any>& cache) {
    auto it = cache.find("electrostatic_potential");
    if (it == cache.end()) {
        throw std::runtime_error("ESP potentials not found in cache. Run compute() first.");
    }

    try {
        return std::any_cast<std::vector<double>>(it->second);
    } catch (const std::bad_any_cast& e) {
        throw std::runtime_error("Failed to retrieve ESP potentials from cache: " +
                                 std::string(e.what()));
    }
}