#include "molecule.h"
#include <Eigen/Core>
#include <Eigen/Geometry>
#include <algorithm>
#include <cassert>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <random>
#include <sstream>
#include <stdexcept>
#include "conformer_generator.h"
#include "props/esp.h"
#include "props/hbond.h"
#include "props/hydrophobicity.h"
#include "props/property_params.h"
#include "surface.h"

#include <GraphMol/DistGeomHelpers/Embedder.h>
#include <GraphMol/FileParsers/MolWriters.h>
#include <GraphMol/FileParsers/FileParsers.h>
#include <GraphMol/FileParsers/MolSupplier.h>
#include <GraphMol/ForceFieldHelpers/MMFF/MMFF.h>
#include <GraphMol/ForceFieldHelpers/UFF/UFF.h>
#include <GraphMol/MolOps.h>
#include <GraphMol/SmilesParse/SmilesParse.h>
#include <GraphMol/SmilesParse/SmilesWrite.h>
#include <open3d/Open3D.h>

Molecule::Molecule(const char* smiles) {
    this->smiles = smiles;
    this->save_smiles_to_mol();
    this->get_charge_from_mol();

    // Note: Conformers are generated by the caller (CLI) as needed
    // This allows for better control over conformer generation parameters

    registerDefaultProperties();
}

Molecule::Molecule(const std::string& filename) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("Cannot open file: " + filename);
    }

    std::string ext = getFileExtension(filename);

    try {
        if (ext == "sdf") {
            // filename, sanitize: true, removeHs: false
            RDKit::SDMolSupplier supplier(filename, true, false);
            if (!supplier.atEnd()) {
                auto romol_ptr = std::unique_ptr<RDKit::ROMol>(supplier.next());
                if (romol_ptr) {
                    mol = std::make_unique<RDKit::RWMol>(*romol_ptr);
                } else {
                    throw std::runtime_error("Failed to parse molecule from SDF file: " + filename);
                }
            } else {
                throw std::runtime_error("No molecules found in SDF file: " + filename);
            }
        } else {
            throw std::runtime_error("Unsupported file format: " + ext +
                                     ". Only SDF files are currently supported.");
        }

        if (!mol) {
            throw std::runtime_error("Failed to parse molecule from file: " + filename);
        }

        smiles = RDKit::MolToSmiles(*mol);

        get_charge_from_mol();

        bool has_valid_3d = false;
        if (mol->getNumConformers() > 0) {
            const RDKit::Conformer& conf = mol->getConformer(0);
            if (conf.is3D()) {
                has_valid_3d = true;
            }
        }

        if (mol->getNumConformers() == 0 || !has_valid_3d) {
            if (mol->getNumConformers() > 0) {
                mol->clearConformers();
            }
            calculate_conformers(1);
        }

    } catch (const std::exception& e) {
        throw std::runtime_error("Error loading molecule from " + filename + ": " + e.what());
    }

    registerDefaultProperties();
}

Molecule::~Molecule() {
}

Molecule::Molecule(Molecule&& other) noexcept
    : smiles(std::move(other.smiles)), charge(other.charge), mol(std::move(other.mol)),
      surface_cache_(std::move(other.surface_cache_)),
      surface_property_cache_(std::move(other.surface_property_cache_)),
      property_registry_(std::move(other.property_registry_)) {
    // Reset the moved-from object
    other.charge = 0;
}

Molecule& Molecule::operator=(Molecule&& other) noexcept {
    if (this != &other) {
        smiles = std::move(other.smiles);
        charge = other.charge;
        mol = std::move(other.mol);
        surface_cache_ = std::move(other.surface_cache_);
        surface_property_cache_ = std::move(other.surface_property_cache_);
        property_registry_ = std::move(other.property_registry_);

        // Reset the moved-from object
        other.charge = 0;
    }
    return *this;
}

std::string Molecule::get_smiles() const {
    return this->smiles;
}

int Molecule::get_charge() const {
    return this->charge;
}

std::unique_ptr<RDKit::ROMol> Molecule::get_mol() const {
    if (this->mol == nullptr) {
        return nullptr;
    }
    return std::make_unique<RDKit::ROMol>(*this->mol);
}

bool Molecule::mol_to_molfile(std::string_view filename) const {
    if (this->mol == nullptr) {
        std::cerr << "Error: Cannot write molfile, molecule is null" << std::endl;
        return false;
    }
    try {
        MolToMolFile(*this->mol, std::string(filename));
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error writing molfile: " << e.what() << std::endl;
        return false;
    }
}

void Molecule::calculate_conformers(unsigned int num_conformers) const {
    if (this->mol == nullptr) {
        std::cout << "Cannot calculate conformers: molecule is null" << std::endl;
        return;
    }
    try {
        RDKit::INT_VECT mol_cids = RDKit::DGeomHelpers::EmbedMultipleConfs(
            *this->mol, static_cast<unsigned int>(num_conformers));

        for (unsigned int cid : mol_cids) {
            try {
                RDKit::MMFF::MMFFOptimizeMolecule(*this->mol, cid);
            } catch (const std::exception&) {
                try {
                    RDKit::UFF::UFFOptimizeMolecule(*this->mol, cid);
                } catch (const std::exception& e) {
                    std::cerr << "Warning: Force field optimization failed for conformer " << cid
                              << ": " << e.what() << std::endl;
                }
            }
        }

    } catch (const std::exception& e) {
        std::cerr << "Error generating conformers: " << e.what() << std::endl;
    }
}

std::unordered_map<int, int> Molecule::generateAdvancedConformers(const ConformerParams& params) {
    if (this->mol == nullptr) {
        std::cerr << "Cannot generate advanced conformers: molecule is null" << std::endl;
        return {};
    }

    try {
        ConformerGenerator generator(params);
        // Convert unique_ptr to shared_ptr for the conformer generator
        std::shared_ptr<RDKit::ROMol> shared_mol(this->mol.get(), [](RDKit::ROMol*) {});
        auto cluster_map = generator.generateConformers(shared_mol);

        // Remove unwanted conformers and keep only the selected ones
        if (!cluster_map.empty()) {
            // Create a new molecule with only the selected conformers
            auto new_mol = std::make_unique<RDKit::RWMol>(*this->mol);
            new_mol->clearConformers();

            // Add only the selected conformers
            for (const auto& [cluster_id, conformer_id] : cluster_map) {
                // Safety check: ensure conformer_id is valid
                if (conformer_id < 0 || static_cast<unsigned int>(conformer_id) >= this->mol->getNumConformers()) {
                    std::cerr << "Warning: Invalid conformer ID " << conformer_id 
                              << " (total conformers: " << this->mol->getNumConformers() 
                              << "), skipping cluster " << cluster_id << std::endl;
                    continue;
                }
                
                auto selected_conf =
                    std::make_unique<RDKit::Conformer>(this->mol->getConformer(conformer_id));
                // Reset the conformer ID to sequential numbering
                selected_conf->setId(new_mol->getNumConformers());
                new_mol->addConformer(selected_conf.release(),
                                      false);  // false = don't assign new ID
            }

            // Replace the original molecule
            this->mol = std::move(new_mol);
        }

        return cluster_map;
    } catch (const std::exception& e) {
        std::cerr << "Error generating advanced conformers: " << e.what() << std::endl;
        return {};
    }
}

void Molecule::save_smiles_to_mol() {
    try {
        std::unique_ptr<RDKit::RWMol> mol(RDKit::SmilesToMol(smiles));
        if (mol == nullptr) {
            throw std::runtime_error("Error parsing SMILES string");
        }
        this->mol = std::move(mol);
    } catch (const std::exception& e) {
        std::cerr << "Error saving smiles to mol: " << e.what() << std::endl;
        this->mol = nullptr;
    }
}

void Molecule::get_charge_from_mol() {
    if (this->mol == nullptr) {
        return;
    }

    this->charge = RDKit::MolOps::getFormalCharge(*this->mol);
}

void Molecule::add_hydrogens_to_mol() {
    if (this->mol == nullptr) {
        return;
    }
    RDKit::MolOps::addHs(*this->mol);
}

void Molecule::add_hydrogens_to_mol_if_needed() {
    if (this->mol == nullptr) {
        return;
    }
    RDKit::MolOps::addHs(*this->mol, false, true);
}

void Molecule::remove_hydrogens_from_mol() {
    if (this->mol == nullptr) {
        return;
    }
    RDKit::MolOps::removeHs(*this->mol);
}

int Molecule::createSurface(unsigned int conformer_id, unsigned int num_vertices, double radius,
                            double density, double hdensity, std::string type, std::string program,
                            std::string sample_method, bool addH) {
    // Check if conformer exists
    if (mol == nullptr || mol->getNumConformers() <= conformer_id) {
        throw std::runtime_error("Conformer " + std::to_string(conformer_id) + " does not exist");
    }

    auto it = surface_cache_.find(conformer_id);
    if (it != surface_cache_.end()) {
        return conformer_id;  // Surface already exists
    }

    if (addH) {
        add_hydrogens_to_mol_if_needed();
    } else {
        remove_hydrogens_from_mol();
    }

    // smiles
    std::string curr_smiles = RDKit::MolToSmiles(*mol);

    auto surface = std::make_shared<Surface>(*this, conformer_id, num_vertices, radius, density,
                                             hdensity, type, program, sample_method);

    if (!addH) {
        add_hydrogens_to_mol_if_needed();
    }

    surface_cache_[conformer_id] = surface;
    return conformer_id;
}

const std::map<int, std::pair<std::string, std::vector<double>>>& Molecule::getSurfaceVertices(
    unsigned int conformer_id) const {
    auto it = surface_cache_.find(conformer_id);
    if (it == surface_cache_.end()) {
        throw std::runtime_error("Surface not found for conformer " + std::to_string(conformer_id));
    }
    return it->second->vertices;
}

void Molecule::clearSurfaceCache() {
    surface_cache_.clear();
}

unsigned int Molecule::getSurfaceVertexCount(unsigned int conformer_id) const {
    auto it = surface_cache_.find(conformer_id);
    if (it == surface_cache_.end()) {
        throw std::runtime_error("Surface not found for conformer " + std::to_string(conformer_id));
    }
    return static_cast<int>(it->second->vertices.size());
}

std::string Molecule::generateSurfaceCacheKey(unsigned int num_vertices, double radius,
                                              double density, double hdensity,
                                              const std::string& type,
                                              const std::string& program) const {
    std::ostringstream oss;
    oss << num_vertices << "_" << radius << "_" << density << "_" << hdensity << "_" << type << "_"
        << program;
    return oss.str();
}

int Molecule::getNumConformers() const {
    if (mol == nullptr) {
        return 0;
    }
    return mol->getNumConformers();
}

std::vector<int> Molecule::getConformerIds() const {
    std::vector<int> ids;
    if (mol == nullptr) {
        return ids;
    }

    unsigned int num_conformers = mol->getNumConformers();
    for (unsigned int i = 0; i < num_conformers; ++i) {
        ids.push_back(i);
    }
    return ids;
}

bool Molecule::transformConformer(unsigned int conformer_id,
                                  const Eigen::Isometry3d& transformation) {
    if (mol == nullptr || mol->getNumConformers() <= conformer_id) {
        throw std::runtime_error("Conformer " + std::to_string(conformer_id) + " does not exist");
    }

    try {
        auto& conf = mol->getConformer(conformer_id);
        int num_atoms = conf.getNumAtoms();

        // Apply transformation to each atom's coordinates
        for (int i = 0; i < num_atoms; ++i) {
            auto pos = conf.getAtomPos(i);
            Eigen::Vector3d coord(pos.x, pos.y, pos.z);

            // Apply transformation (homogeneous coordinates)
            Eigen::Vector3d transformed = transformation * coord;

            // Update the conformer coordinates
            conf.setAtomPos(i, RDGeom::Point3D(transformed.x(), transformed.y(), transformed.z()));
        }

        // Invalidate cached surface for this conformer since coordinates changed
        auto it = surface_cache_.find(conformer_id);
        if (it != surface_cache_.end()) {
            surface_cache_.erase(it);
        }

        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error transforming conformer " << conformer_id << ": " << e.what()
                  << std::endl;
        return false;
    }
}

bool Molecule::transformSurface(unsigned int conformer_id,
                                const Eigen::Isometry3d& transformation) {
    // Check if surface exists for this conformer
    auto it = surface_cache_.find(conformer_id);
    if (it == surface_cache_.end()) {
        throw std::runtime_error("Surface not found for conformer " + std::to_string(conformer_id));
    }

    try {
        // Apply transformation directly to surface vertices
        it->second->transformSurface(transformation);
        return true;
    } catch (const std::exception& e) {
        std::cerr << "Error transforming surface for conformer " << conformer_id << ": " << e.what()
                  << std::endl;
        return false;
    }
}

void Molecule::saveConformerSDF(unsigned int conformer_id, const std::string& filename,
                                bool include_properties) const {
    if (mol == nullptr || mol->getNumConformers() <= conformer_id) {
        throw std::runtime_error("Conformer " + std::to_string(conformer_id) + " does not exist");
    }

    try {
        auto mol_copy = std::make_unique<RDKit::RWMol>(*mol);

        std::vector<int> conformer_ids;
        for (unsigned int i = 0; i < mol_copy->getNumConformers(); ++i) {
            conformer_ids.push_back(i);
        }

        for (unsigned int cid : conformer_ids) {
            if (cid != conformer_id) {
                mol_copy->removeConformer(cid);
            }
        }

        mol_copy->setProp("_Name", "Conformer_" + std::to_string(conformer_id));

        MolToMolFile(*mol_copy, filename);

        if (include_properties) {
            std::ofstream file(filename, std::ios::app);
            if (file.is_open()) {
                file << "> <SMILES>\n";
                file << smiles << "\n\n";
                file << "> <FormalCharge>\n";
                file << get_charge() << "\n\n";
                file << "> <ConformerID>\n";
                file << conformer_id << "\n\n";
                file << "> <NumAtoms>\n";
                file << mol_copy->getNumAtoms() << "\n\n";
                file << "$$$$\n";  // SDF end marker
                file.close();
            }
        }
    } catch (const std::exception& e) {
        throw std::runtime_error("Error saving conformer " + std::to_string(conformer_id) + ": " +
                                 e.what());
    }
}

void Molecule::saveMultiConformerSDF(
    const std::vector<std::pair<int, AlignmentResult>>& conformer_results,
    const std::string& filename, bool include_properties) const {
    if (mol == nullptr) {
        throw std::runtime_error("Molecule is null");
    }

    try {
        std::ofstream file(filename);
        if (!file.is_open()) {
            throw std::runtime_error("Cannot open file for writing: " + filename);
        }

        for (const auto& [conformer_id, alignment_result] : conformer_results) {
            if (conformer_id >= static_cast<int>(mol->getNumConformers())) {
                std::cerr << "Warning: Conformer " << conformer_id << " does not exist, skipping..."
                          << std::endl;
                continue;
            }

            // Create a copy of the molecule with only this conformer
            auto mol_copy = std::make_unique<RDKit::RWMol>(*mol);

            // Remove all conformers except the one we want
            std::vector<int> conformer_ids_to_remove;
            for (unsigned int i = 0; i < mol_copy->getNumConformers(); ++i) {
                if (static_cast<int>(i) != conformer_id) {
                    conformer_ids_to_remove.push_back(i);
                }
            }

            // Remove conformers in reverse order to maintain indices
            for (auto it = conformer_ids_to_remove.rbegin(); it != conformer_ids_to_remove.rend();
                 ++it) {
                mol_copy->removeConformer(*it);
            }

            // Set molecule name
            mol_copy->setProp("_Name", "Conformer_" + std::to_string(conformer_id));

            // Write the conformer to file
            std::string mol_block = MolToMolBlock(*mol_copy);
            file << mol_block;

            if (include_properties) {
                // Add alignment scores as SDF properties
                file << "> <SMILES>\n";
                file << smiles << "\n\n";
                file << "> <FormalCharge>\n";
                file << get_charge() << "\n\n";
                file << "> <ConformerID>\n";
                file << conformer_id << "\n\n";
                file << "> <NumAtoms>\n";
                file << mol_copy->getNumAtoms() << "\n\n";
                file << "> <AlignmentFitness>\n";
                file << std::fixed << std::setprecision(6) << alignment_result.fitness << "\n\n";
                file << "> <AlignmentRMSE>\n";
                file << std::fixed << std::setprecision(6) << alignment_result.inlier_rmse
                     << "\n\n";
                file << "> <UsedColoredICP>\n";
                file << (alignment_result.used_colored_icp ? "true" : "false") << "\n\n";

                // Add transformation matrix as properties
                const auto& matrix = alignment_result.transformation.matrix();
                file << "> <TransformationMatrix>\n";
                for (int i = 0; i < 4; ++i) {
                    for (int j = 0; j < 4; ++j) {
                        if (i > 0 || j > 0)
                            file << " ";
                        file << std::fixed << std::setprecision(6) << matrix(i, j);
                    }
                }
                file << "\n\n";
            }

            file << "$$$$\n";  // SDF end marker
        }

        file.close();

    } catch (const std::exception& e) {
        throw std::runtime_error("Error saving multi-conformer SDF: " + std::string(e.what()));
    }
}

void Molecule::saveSurfacePointCloud(unsigned int conformer_id, const std::string& filename,
                                     bool include_normals, bool include_colors,
                                     const std::vector<std::string>& properties) const {
    auto it = surface_cache_.find(conformer_id);
    if (it == surface_cache_.end()) {
        throw std::runtime_error("Surface not found for conformer " + std::to_string(conformer_id));
    }

    // Get property cache for this surface if available
    // Combine all property caches into a single cache for multiple properties
    std::unordered_map<std::string, std::any> combined_cache;
    if (!properties.empty()) {
        for (const auto& property : properties) {
            std::string cache_key = std::to_string(conformer_id) + "_" + property;
            auto cache_it = surface_property_cache_.find(cache_key);
            if (cache_it != surface_property_cache_.end()) {
                // Merge the individual property cache into combined cache
                for (const auto& [key, value] : cache_it->second) {
                    combined_cache[key] = value;
                }
            }
        }
    }

    const std::unordered_map<std::string, std::any>* property_cache = nullptr;
    if (!combined_cache.empty()) {
        property_cache = &combined_cache;
    }

    it->second->savePointCloud(filename, include_normals, include_colors, properties,
                               property_cache);
}

void Molecule::saveSurfaceMesh(unsigned int conformer_id, const std::string& filename,
                               bool include_normals, bool include_colors,
                               const std::vector<std::string>& properties) const {
    auto it = surface_cache_.find(conformer_id);
    if (it == surface_cache_.end()) {
        throw std::runtime_error("Surface not found for conformer " + std::to_string(conformer_id));
    }

    // Get property cache for this surface if available
    // Combine all property caches into a single cache for multiple properties
    std::unordered_map<std::string, std::any> combined_cache;
    if (!properties.empty()) {
        for (const auto& property : properties) {
            std::string cache_key = std::to_string(conformer_id) + "_" + property;
            auto cache_it = surface_property_cache_.find(cache_key);
            if (cache_it != surface_property_cache_.end()) {
                // Merge the individual property cache into combined cache
                for (const auto& [key, value] : cache_it->second) {
                    combined_cache[key] = value;
                }
            }
        }
    }

    const std::unordered_map<std::string, std::any>* property_cache = nullptr;
    if (!combined_cache.empty()) {
        property_cache = &combined_cache;
    }

    it->second->saveMesh(filename, include_normals, include_colors, properties, property_cache);
}

std::vector<std::unique_ptr<Molecule>> Molecule::loadFromMultiMolFile(const std::string& filename) {
    std::vector<std::unique_ptr<Molecule>> molecules;

    std::string ext = getFileExtension(filename);
    if (ext != "sdf") {
        throw std::runtime_error("Multi-molecule loading only supported for SDF files");
    }

    try {
        RDKit::SDMolSupplier supplier(filename);

        while (!supplier.atEnd()) {
            auto romol_ptr = std::unique_ptr<RDKit::ROMol>(supplier.next());
            if (romol_ptr) {
                std::string temp_smiles =
                    "Loaded from " + filename + "_mol_" + std::to_string(molecules.size() + 1);
                auto temp_mol = std::make_unique<Molecule>(temp_smiles.c_str());
                temp_mol->mol = std::make_unique<RDKit::RWMol>(*romol_ptr);

                temp_mol->get_charge_from_mol();

                // Move the unique_ptr into the vector - NO raw pointers!
                molecules.push_back(std::move(temp_mol));
            }
        }

        if (molecules.empty()) {
            throw std::runtime_error("No molecules found in file: " + filename);
        }

    } catch (const std::exception& e) {
        throw std::runtime_error("Error loading molecules from " + filename + ": " + e.what());
    }

    return molecules;
}

std::string Molecule::getFileExtension(const std::string& filename) {
    size_t dot_pos = filename.find_last_of('.');
    if (dot_pos == std::string::npos) {
        throw std::runtime_error("No file extension found in: " + filename);
    }

    std::string ext = filename.substr(dot_pos + 1);
    std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
    return ext;
}

void Molecule::compute(const std::string& property_name, unsigned int conformer_id,
                       SurfaceParams surface_params) {
    // Check if property is registered
    auto registry_it = property_registry_.find(property_name);
    if (registry_it == property_registry_.end()) {
        throw std::runtime_error("Property '" + property_name +
                                 "' is not registered. Available properties: " + [this]() {
                                     std::string available;
                                     for (const auto& pair : property_registry_) {
                                         if (!available.empty())
                                             available += ", ";
                                         available += pair.first;
                                     }
                                     return available.empty() ? "none" : available;
                                 }());
    }


    int surface_id =
        createSurface(conformer_id, surface_params.num_vertices, surface_params.radius,
                      surface_params.density, surface_params.hdensity, surface_params.type,
                      surface_params.program, surface_params.sample_method, surface_params.addH);

    // Get the surface object
    auto surface_it = surface_cache_.find(surface_id);
    if (surface_it == surface_cache_.end()) {
        throw std::runtime_error("Surface not found after creation");
    }

    std::shared_ptr<Surface> surface = surface_it->second;

    // Create property object using the factory
    std::unique_ptr<ISurfaceProperty> property;

    // print property name and smiles
    auto curr_smiles = RDKit::MolToSmiles(*mol);
    // Special handling for ESP property to use the charge method from surface_params
    if (property_name == "esp") {
        property = std::make_unique<SurfaceESPProperty>(surface_params.charge_method);
    } else {
        property = registry_it->second();
    }

    // Create property cache
    std::unordered_map<std::string, std::any> cache;

    // Compute the property
    property->compute(*surface, cache);

    // Store the cache using surface_id + property_name as key
    surface_property_cache_[std::to_string(surface_id) + "_" + property_name] = cache;
}

void Molecule::registerProperty(const std::string& property_name,
                                std::function<std::unique_ptr<ISurfaceProperty>()> factory) {
    property_registry_[property_name] = factory;
}

void Molecule::generate3DCoordinates() {
    if (mol == nullptr)
        return;

    // Check if molecule already has 3D coordinates
    bool has_3d = false;
    if (mol->getNumConformers() > 0) {
        const auto& conf = mol->getConformer();
        if (conf.is3D()) {
            has_3d = true;
        }
    }

    // Generate 3D coordinates if not present
    if (!has_3d) {
        generateSingleConformer();
    }
}

void Molecule::generateSingleConformer() {
    if (mol == nullptr)
        return;

    try {
        int cid = RDKit::DGeomHelpers::EmbedMolecule(*mol);

        if (cid >= 0) {
            try {
                RDKit::MMFF::MMFFOptimizeMolecule(*mol, cid);
            } catch (const std::exception&) {
                try {
                    RDKit::UFF::UFFOptimizeMolecule(*mol, cid);
                } catch (const std::exception& e) {
                    std::cerr << "Warning: Force field optimization failed for single conformer: "
                              << e.what() << std::endl;
                }
            }
        } else {
            std::cerr << "Error: Failed to generate conformer using RDKit" << std::endl;
        }

    } catch (const std::exception& e) {
        std::cerr << "Error generating single conformer: " << e.what() << std::endl;
    }
}

void Molecule::registerDefaultProperties() {
    // Register ESP property
    registerProperty("esp",
                     []() { return std::make_unique<SurfaceESPProperty>(ChargeMethod::RDKIT); });

    // Register hydrophobicity property
    registerProperty("hydrophobicity", []() { return std::make_unique<HydrophobicityProperty>(); });

    // Register hydrogen bond property
    registerProperty("hbond", []() { return std::make_unique<HBondProperty>(); });

    // Future properties can be registered here:
    // registerProperty("hydrophobicity", []() { return
    // std::make_unique<SurfaceHydrophobicityProperty>(); }); registerProperty("electrostatics",
    // []() { return std::make_unique<SurfaceElectrostaticsProperty>(); });
}

void Molecule::registerAllProperties() {
    // Register all currently available properties
    registerProperty("esp",
                     []() { return std::make_unique<SurfaceESPProperty>(ChargeMethod::RDKIT); });

    registerProperty("hydrophobicity", []() { return std::make_unique<HydrophobicityProperty>(); });

    registerProperty("hbond", []() { return std::make_unique<HBondProperty>(); });
}

std::vector<std::string> Molecule::getRegisteredProperties() const {
    std::vector<std::string> properties;
    for (const auto& pair : property_registry_) {
        properties.push_back(pair.first);
    }
    return properties;
}

Eigen::Isometry3d Molecule::align_to_molecule(Molecule& target_mol,
                                              unsigned int target_conformer_id,
                                              unsigned int source_conformer_id) {
    // Check if conformers exist
    if (mol == nullptr || mol->getNumConformers() <= source_conformer_id) {
        throw std::runtime_error("Source conformer " + std::to_string(source_conformer_id) +
                                 " does not exist");
    }
    if (target_mol.mol == nullptr || target_mol.mol->getNumConformers() <= target_conformer_id) {
        throw std::runtime_error("Target conformer " + std::to_string(target_conformer_id) +
                                 " does not exist");
    }

    // Check if surfaces exist
    auto source_surface_it = surface_cache_.find(source_conformer_id);
    if (source_surface_it == surface_cache_.end()) {
        throw std::runtime_error("Source surface for conformer " +
                                 std::to_string(source_conformer_id) + " not found");
    }

    auto target_surface_it = target_mol.surface_cache_.find(target_conformer_id);
    if (target_surface_it == target_mol.surface_cache_.end()) {
        throw std::runtime_error("Target surface for conformer " +
                                 std::to_string(target_conformer_id) + " not found");
    }

    // Get surfaces
    std::shared_ptr<Surface> source_surface = source_surface_it->second;
    std::shared_ptr<Surface> target_surface = target_surface_it->second;

    // ESP properties should be computed before calling alignment
    // Alignment method only uses already computed properties for coloring

    // Create Open3D point clouds with colors
    auto source_cloud = std::make_shared<open3d::geometry::PointCloud>();
    auto target_cloud = std::make_shared<open3d::geometry::PointCloud>();

    // Convert source surface to Open3D point cloud with existing normals
    for (const auto& vertex_pair : source_surface->vertices) {
        const auto& coords = vertex_pair.second.second;
        if (coords.size() >= 3) {
            source_cloud->points_.emplace_back(coords[0], coords[1], coords[2]);
            // Use existing normals if available (elements 3-5), otherwise add empty normal
            if (coords.size() >= 6) {
                source_cloud->normals_.emplace_back(coords[3], coords[4], coords[5]);
            } else {
                source_cloud->normals_.emplace_back(0.0, 0.0, 0.0);
            }
        }
    }

    // Convert target surface to Open3D point cloud with existing normals
    for (const auto& vertex_pair : target_surface->vertices) {
        const auto& coords = vertex_pair.second.second;
        if (coords.size() >= 3) {
            target_cloud->points_.emplace_back(coords[0], coords[1], coords[2]);
            // Use existing normals if available (elements 3-5), otherwise add empty normal
            if (coords.size() >= 6) {
                target_cloud->normals_.emplace_back(coords[3], coords[4], coords[5]);
            } else {
                target_cloud->normals_.emplace_back(0.0, 0.0, 0.0);
            }
        }
    }

    // Add colors based on ALL computed properties for better alignment
    bool has_source_colors = false;
    bool has_target_colors = false;

    // Helper function to get property values from cache - completely dynamic
    auto getPropertyValues =
        [](const std::map<std::string, std::unordered_map<std::string, std::any>>& cache,
           unsigned int conformer_id, const std::string& property_name) -> std::vector<double> {
        std::string cache_key = std::to_string(conformer_id) + "_" + property_name;
        auto cache_it = cache.find(cache_key);
        if (cache_it != cache.end()) {
            // Try common value key patterns dynamically
            std::vector<std::string> possible_keys = {
                property_name + "_values",     // e.g., "esp_values"
                "electrostatic_potential",     // ESP specific
                property_name + "_potential",  // e.g., "hbond_potential"
                property_name + "_charges",    // e.g., "esp_charges"
                property_name                  // Direct property name
            };

            for (const auto& key : possible_keys) {
                auto values_it = cache_it->second.find(key);
                if (values_it != cache_it->second.end()) {
                    try {
                        return std::any_cast<std::vector<double>>(values_it->second);
                    } catch (const std::exception&) {
                        // Try next key
                        continue;
                    }
                }
            }
        }
        return {};
    };

    // Helper function to normalize property value to [-1, 1] range using PropertyParamsRegistry
    auto normalizePropertyValue = [](const std::string& property_name, double value) -> double {
        try {
            // Use PropertyParamsRegistry for dynamic property parameters
            PropertyParams params = PropertyParamsRegistry::getParams(property_name);
            double min_val = params.min_value;
            double max_val = params.max_value;

            if (max_val > min_val) {
                double normalized = (value - min_val) / (max_val - min_val);
                normalized = std::max(0.0, std::min(1.0, normalized));  // Clamp to [0, 1]
                return 2.0 * normalized - 1.0;                          // Convert to [-1, 1]
            }
        } catch (const std::exception&) {
            // Property not found in registry, use default range
            double min_val = -1.0, max_val = 1.0;
            double normalized = (value - min_val) / (max_val - min_val);
            normalized = std::max(0.0, std::min(1.0, normalized));
            return 2.0 * normalized - 1.0;
        }
        return 0.0;
    };

    // Get all available properties from source - completely dynamic
    std::vector<std::string> available_properties;
    std::string conformer_prefix = std::to_string(source_conformer_id) + "_";

    for (const auto& [key, _] : surface_property_cache_) {
        if (key.find(conformer_prefix) == 0) {
            std::string property_name = key.substr(conformer_prefix.length());

            // Check if this property has actual values (not just min/max)
            auto values =
                getPropertyValues(surface_property_cache_, source_conformer_id, property_name);
            if (!values.empty()) {
                available_properties.push_back(property_name);
            }
        }
    }

    if (!available_properties.empty()) {
        source_cloud->colors_.clear();
        source_cloud->colors_.reserve(source_cloud->points_.size());

        for (size_t i = 0; i < source_cloud->points_.size(); ++i) {
            Eigen::Vector3d combined_color(0.0, 0.0, 0.0);
            int valid_properties = 0;

            for (const auto& property : available_properties) {
                auto values =
                    getPropertyValues(surface_property_cache_, source_conformer_id, property);
                if (i < values.size()) {
                    double normalized_value = normalizePropertyValue(property, values[i]);

                    // Dynamic color mapping based on property name patterns
                    // This creates a unique color signature for each property type
                    std::hash<std::string> hasher;
                    size_t hash = hasher(property);

                    // Use hash to create consistent color components for each property
                    double r_factor = ((hash & 0xFF) / 255.0) * 0.5 + 0.25;  // 0.25 to 0.75
                    double g_factor = (((hash >> 8) & 0xFF) / 255.0) * 0.5 + 0.25;
                    double b_factor = (((hash >> 16) & 0xFF) / 255.0) * 0.5 + 0.25;

                    // Add property contribution to combined color
                    combined_color[0] += r_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[1] += g_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[2] += b_factor * (1.0 + normalized_value) / 2.0;

                    valid_properties++;
                }
            }

            if (valid_properties > 0) {
                combined_color /= valid_properties;  // Average the colors
                // Ensure colors are in valid range
                combined_color = combined_color.cwiseMax(Eigen::Vector3d::Zero())
                                     .cwiseMin(Eigen::Vector3d::Ones());
                source_cloud->colors_.push_back(combined_color);
            } else {
                source_cloud->colors_.emplace_back(0.5, 0.5, 0.5);  // Gray fallback
            }
        }
        has_source_colors = true;
    }

    if (!available_properties.empty()) {
        target_cloud->colors_.clear();
        target_cloud->colors_.reserve(target_cloud->points_.size());

        for (size_t i = 0; i < target_cloud->points_.size(); ++i) {
            Eigen::Vector3d combined_color(0.0, 0.0, 0.0);
            int valid_properties = 0;

            for (const auto& property : available_properties) {
                auto values = getPropertyValues(target_mol.surface_property_cache_,
                                                target_conformer_id, property);
                if (i < values.size()) {
                    double normalized_value = normalizePropertyValue(property, values[i]);

                    // Dynamic color mapping based on property name patterns
                    // This creates a unique color signature for each property type
                    std::hash<std::string> hasher;
                    size_t hash = hasher(property);

                    // Use hash to create consistent color components for each property
                    double r_factor = ((hash & 0xFF) / 255.0) * 0.5 + 0.25;  // 0.25 to 0.75
                    double g_factor = (((hash >> 8) & 0xFF) / 255.0) * 0.5 + 0.25;
                    double b_factor = (((hash >> 16) & 0xFF) / 255.0) * 0.5 + 0.25;

                    // Add property contribution to combined color
                    combined_color[0] += r_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[1] += g_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[2] += b_factor * (1.0 + normalized_value) / 2.0;

                    valid_properties++;
                }
            }

            if (valid_properties > 0) {
                combined_color /= valid_properties;  // Average the colors
                // Ensure colors are in valid range
                combined_color = combined_color.cwiseMax(Eigen::Vector3d::Zero())
                                     .cwiseMin(Eigen::Vector3d::Ones());
                target_cloud->colors_.push_back(combined_color);
            } else {
                target_cloud->colors_.emplace_back(0.5, 0.5, 0.5);  // Gray fallback
            }
        }
        has_target_colors = true;
    }

    // Set uniform colors if no property colors are available
    if (!has_source_colors) {
        source_cloud->colors_.resize(source_cloud->points_.size(),
                                     Eigen::Vector3d(0.5, 0.5, 0.5));  // Gray
    }
    if (!has_target_colors) {
        target_cloud->colors_.resize(target_cloud->points_.size(),
                                     Eigen::Vector3d(0.5, 0.5, 0.5));  // Gray
    }

    // Set up ICP parameters
    double voxel_size = 1.0;  // Angstroms
    auto source_down = source_cloud->VoxelDownSample(voxel_size);
    auto target_down = target_cloud->VoxelDownSample(voxel_size);

    // Ensure normals are available for registration
    // Strategy: Use existing normals from surface vertices when available,
    //           otherwise fall back to Open3D normal estimation
    if (source_down->normals_.empty()) {
        source_down->EstimateNormals();
    }
    if (target_down->normals_.empty()) {
        target_down->EstimateNormals();
    }

    open3d::pipelines::registration::RegistrationResult result;

    // Prioritize colored ICP if properties are available
    if (has_source_colors && has_target_colors && !available_properties.empty()) {
        try {
#ifdef DEBUG
            std::cout << "Attempting colored ICP registration with " << available_properties.size()
                      << " properties..." << std::endl;
#endif
            result = open3d::pipelines::registration::RegistrationColoredICP(
                *source_down, *target_down, voxel_size, Eigen::Matrix4d::Identity(),
                open3d::pipelines::registration::TransformationEstimationForColoredICP(),
                open3d::pipelines::registration::ICPConvergenceCriteria(1e-6, 1e-6, 50));
#ifdef DEBUG
            std::cout << "✓ Used colored ICP registration with property-based colors (fitness: "
                      << result.fitness_ << ")" << std::endl;
#endif
        } catch (const std::exception& e) {
            std::cerr << "Warning: Colored ICP failed, falling back to standard ICP: " << e.what()
                      << std::endl;
            result = open3d::pipelines::registration::RegistrationICP(
                *source_down, *target_down, voxel_size * 2.0, Eigen::Matrix4d::Identity(),
                open3d::pipelines::registration::TransformationEstimationPointToPoint(),
                open3d::pipelines::registration::ICPConvergenceCriteria(1e-6, 1e-6, 30));
#ifdef DEBUG
            std::cout << "Used standard ICP registration (fitness: " << result.fitness_ << ")"
                      << std::endl;
#endif
        }
    } else {
// Fallback to standard ICP
#ifdef DEBUG
        std::cout << "No properties available, using standard ICP registration..." << std::endl;
#endif
        result = open3d::pipelines::registration::RegistrationICP(
            *source_down, *target_down, voxel_size * 2.0, Eigen::Matrix4d::Identity(),
            open3d::pipelines::registration::TransformationEstimationPointToPoint(),
            open3d::pipelines::registration::ICPConvergenceCriteria(1e-6, 1e-6, 30));
#ifdef DEBUG
        std::cout << "Used standard ICP registration (fitness: " << result.fitness_ << ")"
                  << std::endl;
#endif
    }

#ifdef DEBUG
    std::cout << "Registration completed!" << std::endl;
    std::cout << "Fitness: " << result.fitness_ << std::endl;
    std::cout << "Inlier RMSE: " << result.inlier_rmse_ << std::endl;
#endif
    // Convert Open3D matrix to Eigen Isometry3d
    Eigen::Isometry3d transformation;
    transformation.matrix() = result.transformation_;

    return transformation;
}

Molecule::AlignmentResult Molecule::align_to_molecule_detailed(Molecule& target_mol,
                                                               unsigned int target_conformer_id,
                                                               unsigned int source_conformer_id) {
    // Check if conformers exist
    if (mol == nullptr || mol->getNumConformers() <= source_conformer_id) {
        throw std::runtime_error("Source conformer " + std::to_string(source_conformer_id) +
                                 " does not exist");
    }
    if (target_mol.mol == nullptr || target_mol.mol->getNumConformers() <= target_conformer_id) {
        throw std::runtime_error("Target conformer " + std::to_string(target_conformer_id) +
                                 " does not exist");
    }

    // Check if surfaces exist
    auto source_surface_it = surface_cache_.find(source_conformer_id);
    if (source_surface_it == surface_cache_.end()) {
        throw std::runtime_error("Source surface for conformer " +
                                 std::to_string(source_conformer_id) + " not found");
    }

    auto target_surface_it = target_mol.surface_cache_.find(target_conformer_id);
    if (target_surface_it == target_mol.surface_cache_.end()) {
        throw std::runtime_error("Target surface for conformer " +
                                 std::to_string(target_conformer_id) + " not found");
    }

    // Get surfaces
    std::shared_ptr<Surface> source_surface = source_surface_it->second;
    std::shared_ptr<Surface> target_surface = target_surface_it->second;

    // Create Open3D point clouds with colors
    auto source_cloud = std::make_shared<open3d::geometry::PointCloud>();
    auto target_cloud = std::make_shared<open3d::geometry::PointCloud>();

    // Convert source surface to Open3D point cloud with existing normals
    for (const auto& vertex_pair : source_surface->vertices) {
        const auto& coords = vertex_pair.second.second;
        if (coords.size() >= 3) {
            source_cloud->points_.emplace_back(coords[0], coords[1], coords[2]);
            // Use existing normals if available (elements 3-5), otherwise add empty normal
            if (coords.size() >= 6) {
                source_cloud->normals_.emplace_back(coords[3], coords[4], coords[5]);
            } else {
                source_cloud->normals_.emplace_back(0.0, 0.0, 0.0);
            }
        }
    }

    // Convert target surface to Open3D point cloud with existing normals
    for (const auto& vertex_pair : target_surface->vertices) {
        const auto& coords = vertex_pair.second.second;
        if (coords.size() >= 3) {
            target_cloud->points_.emplace_back(coords[0], coords[1], coords[2]);
            // Use existing normals if available (elements 3-5), otherwise add empty normal
            if (coords.size() >= 6) {
                target_cloud->normals_.emplace_back(coords[3], coords[4], coords[5]);
            } else {
                target_cloud->normals_.emplace_back(0.0, 0.0, 0.0);
            }
        }
    }

    // Add colors based on ALL computed properties for better alignment
    bool has_source_colors = false;
    bool has_target_colors = false;

    // Helper function to get property values from cache - completely dynamic
    auto getPropertyValues =
        [](const std::map<std::string, std::unordered_map<std::string, std::any>>& cache,
           unsigned int conformer_id, const std::string& property_name) -> std::vector<double> {
        std::string cache_key = std::to_string(conformer_id) + "_" + property_name;
        auto cache_it = cache.find(cache_key);
        if (cache_it != cache.end()) {
            // Try common value key patterns dynamically
            std::vector<std::string> possible_keys = {
                property_name + "_values",     // e.g., "esp_values"
                "electrostatic_potential",     // ESP specific
                property_name + "_potential",  // e.g., "hbond_potential"
                property_name + "_charges",    // e.g., "esp_charges"
                property_name                  // Direct property name
            };

            for (const auto& key : possible_keys) {
                auto values_it = cache_it->second.find(key);
                if (values_it != cache_it->second.end()) {
                    try {
                        return std::any_cast<std::vector<double>>(values_it->second);
                    } catch (const std::exception&) {
                        // Try next key
                        continue;
                    }
                }
            }
        }
        return {};
    };

    // Helper function to normalize property value to [-1, 1] range using PropertyParamsRegistry
    auto normalizePropertyValue = [](const std::string& property_name, double value) -> double {
        try {
            // Use PropertyParamsRegistry for dynamic property parameters
            PropertyParams params = PropertyParamsRegistry::getParams(property_name);
            double min_val = params.min_value;
            double max_val = params.max_value;

            if (max_val > min_val) {
                double normalized = (value - min_val) / (max_val - min_val);
                normalized = std::max(0.0, std::min(1.0, normalized));  // Clamp to [0, 1]
                return 2.0 * normalized - 1.0;                          // Convert to [-1, 1]
            }
        } catch (const std::exception&) {
            // Property not found in registry, use default range
            double min_val = -1.0, max_val = 1.0;
            double normalized = (value - min_val) / (max_val - min_val);
            normalized = std::max(0.0, std::min(1.0, normalized));
            return 2.0 * normalized - 1.0;
        }
        return 0.0;
    };

    // Get all available properties from source - completely dynamic
    std::vector<std::string> available_properties;
    std::string conformer_prefix = std::to_string(source_conformer_id) + "_";

    for (const auto& [key, _] : surface_property_cache_) {
        if (key.find(conformer_prefix) == 0) {
            std::string property_name = key.substr(conformer_prefix.length());

            // Check if this property has actual values (not just min/max)
            auto values =
                getPropertyValues(surface_property_cache_, source_conformer_id, property_name);
            if (!values.empty()) {
                available_properties.push_back(property_name);
            }
        }
    }

    if (!available_properties.empty()) {
        source_cloud->colors_.clear();
        source_cloud->colors_.reserve(source_cloud->points_.size());

        for (size_t i = 0; i < source_cloud->points_.size(); ++i) {
            Eigen::Vector3d combined_color(0.0, 0.0, 0.0);
            int valid_properties = 0;

            for (const auto& property : available_properties) {
                auto values =
                    getPropertyValues(surface_property_cache_, source_conformer_id, property);
                if (i < values.size()) {
                    double normalized_value = normalizePropertyValue(property, values[i]);

                    // Dynamic color mapping based on property name patterns
                    // This creates a unique color signature for each property type
                    std::hash<std::string> hasher;
                    size_t hash = hasher(property);

                    // Use hash to create consistent color components for each property
                    double r_factor = ((hash & 0xFF) / 255.0) * 0.5 + 0.25;  // 0.25 to 0.75
                    double g_factor = (((hash >> 8) & 0xFF) / 255.0) * 0.5 + 0.25;
                    double b_factor = (((hash >> 16) & 0xFF) / 255.0) * 0.5 + 0.25;

                    // Add property contribution to combined color
                    combined_color[0] += r_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[1] += g_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[2] += b_factor * (1.0 + normalized_value) / 2.0;

                    valid_properties++;
                }
            }

            if (valid_properties > 0) {
                combined_color /= valid_properties;  // Average the colors
                // Ensure colors are in valid range
                combined_color = combined_color.cwiseMax(Eigen::Vector3d::Zero())
                                     .cwiseMin(Eigen::Vector3d::Ones());
                source_cloud->colors_.push_back(combined_color);
            } else {
                source_cloud->colors_.emplace_back(0.5, 0.5, 0.5);  // Gray fallback
            }
        }
        has_source_colors = true;
    }

    if (!available_properties.empty()) {
        target_cloud->colors_.clear();
        target_cloud->colors_.reserve(target_cloud->points_.size());

        for (size_t i = 0; i < target_cloud->points_.size(); ++i) {
            Eigen::Vector3d combined_color(0.0, 0.0, 0.0);
            int valid_properties = 0;

            for (const auto& property : available_properties) {
                auto values = getPropertyValues(target_mol.surface_property_cache_,
                                                target_conformer_id, property);
                if (i < values.size()) {
                    double normalized_value = normalizePropertyValue(property, values[i]);

                    // Dynamic color mapping based on property name patterns
                    // This creates a unique color signature for each property type
                    std::hash<std::string> hasher;
                    size_t hash = hasher(property);

                    // Use hash to create consistent color components for each property
                    double r_factor = ((hash & 0xFF) / 255.0) * 0.5 + 0.25;  // 0.25 to 0.75
                    double g_factor = (((hash >> 8) & 0xFF) / 255.0) * 0.5 + 0.25;
                    double b_factor = (((hash >> 16) & 0xFF) / 255.0) * 0.5 + 0.25;

                    // Add property contribution to combined color
                    combined_color[0] += r_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[1] += g_factor * (1.0 + normalized_value) / 2.0;
                    combined_color[2] += b_factor * (1.0 + normalized_value) / 2.0;

                    valid_properties++;
                }
            }

            if (valid_properties > 0) {
                combined_color /= valid_properties;  // Average the colors
                // Ensure colors are in valid range
                combined_color = combined_color.cwiseMax(Eigen::Vector3d::Zero())
                                     .cwiseMin(Eigen::Vector3d::Ones());
                target_cloud->colors_.push_back(combined_color);
            } else {
                target_cloud->colors_.emplace_back(0.5, 0.5, 0.5);  // Gray fallback
            }
        }
        has_target_colors = true;
    }

    // Set uniform colors if no property colors are available
    if (!has_source_colors) {
        source_cloud->colors_.resize(source_cloud->points_.size(),
                                     Eigen::Vector3d(0.5, 0.5, 0.5));  // Gray
    }
    if (!has_target_colors) {
        target_cloud->colors_.resize(target_cloud->points_.size(),
                                     Eigen::Vector3d(0.5, 0.5, 0.5));  // Gray
    }

    // Set up ICP parameters
    double voxel_size = 1.0;  // Angstroms
    auto source_down = source_cloud->VoxelDownSample(voxel_size);
    auto target_down = target_cloud->VoxelDownSample(voxel_size);

    // Ensure normals are available for registration
    // Strategy: Use existing normals from surface vertices when available,
    //           otherwise fall back to Open3D normal estimation
    if (source_down->normals_.empty()) {
        source_down->EstimateNormals();
    }
    if (target_down->normals_.empty()) {
        target_down->EstimateNormals();
    }

    open3d::pipelines::registration::RegistrationResult result;
    bool used_colored_icp = false;

    // Prioritize colored ICP if properties are available
    if (has_source_colors && has_target_colors && !available_properties.empty()) {
        try {
#ifdef DEBUG
            std::cout << "Attempting colored ICP registration with " << available_properties.size()
                      << " properties..." << std::endl;
#endif
            result = open3d::pipelines::registration::RegistrationColoredICP(
                *source_down, *target_down, voxel_size, Eigen::Matrix4d::Identity(),
                open3d::pipelines::registration::TransformationEstimationForColoredICP(),
                open3d::pipelines::registration::ICPConvergenceCriteria(1e-6, 1e-6, 50));
            used_colored_icp = true;
#ifdef DEBUG
            std::cout << "✓ Used colored ICP registration with property-based colors (fitness: "
                      << result.fitness_ << ")" << std::endl;
#endif
        } catch (const std::exception& e) {
            std::cerr << "Warning: Colored ICP failed, falling back to standard ICP: " << e.what()
                      << std::endl;
            result = open3d::pipelines::registration::RegistrationICP(
                *source_down, *target_down, voxel_size * 2.0, Eigen::Matrix4d::Identity(),
                open3d::pipelines::registration::TransformationEstimationPointToPoint(),
                open3d::pipelines::registration::ICPConvergenceCriteria(1e-6, 1e-6, 30));
#ifdef DEBUG
            std::cout << "Used standard ICP registration (fitness: " << result.fitness_ << ")"
                      << std::endl;
#endif
        }
    } else {
// Fallback to standard ICP
#ifdef DEBUG
        std::cout << "No properties available, using standard ICP registration..." << std::endl;
#endif
        result = open3d::pipelines::registration::RegistrationICP(
            *source_down, *target_down, voxel_size * 2.0, Eigen::Matrix4d::Identity(),
            open3d::pipelines::registration::TransformationEstimationPointToPoint(),
            open3d::pipelines::registration::ICPConvergenceCriteria(1e-6, 1e-6, 30));
#ifdef DEBUG
        std::cout << "Used standard ICP registration (fitness: " << result.fitness_ << ")"
                  << std::endl;
#endif
    }

#ifdef DEBUG
    std::cout << "Registration completed!" << std::endl;
    std::cout << "Fitness: " << result.fitness_ << std::endl;
    std::cout << "Inlier RMSE: " << result.inlier_rmse_ << std::endl;
#endif

    // Convert Open3D matrix to Eigen Isometry3d
    Eigen::Isometry3d transformation;
    transformation.matrix() = result.transformation_;

    // Return detailed alignment result
    AlignmentResult alignment_result;
    alignment_result.transformation = transformation;
    alignment_result.fitness = result.fitness_;
    alignment_result.inlier_rmse = result.inlier_rmse_;
    alignment_result.used_colored_icp = used_colored_icp;

    return alignment_result;
}
